version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gdash-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    container_name: gdash-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=gdash
    volumes:
      - mongo-data:/data/db
      # Mount init scripts (executed only if DB dir is empty)
      - ../mongo:/docker-entrypoint-initdb.d:ro

  nest-api:
    build:
      context: ../nest-app
      dockerfile: src/Dockerfile
    container_name: gdash-nest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/gdash
      - JWT_SECRET=supersecret
      - NODE_ENV=production
    depends_on:
      - mongo

  python-producer:
    build: ../python-producer
    container_name: gdash-python-producer
    restart: unless-stopped
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - CITY=Pelotas
      - QUEUE=weather-data
    depends_on:
      - rabbitmq

  node-worker:
    build: ../node-worker
    container_name: gdash-node-worker
    restart: unless-stopped
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - API_URL=http://nest-api:3000
    depends_on:
      - rabbitmq
      - nest-api

  frontend:
    build:
      context: ../FRONTEND
      dockerfile: Dockerfile
    container_name: gdash-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://nest-api:3000/api
    depends_on:
      - nest-api

volumes:
  mongo-data: {}